### ISSUE TITLE
[enhancement] We kind of still want the auto matching system right?

### ISSUE THREAD

**Issue by karaika10** [RUEEE/th19p2vp#1]
需求的原因是目前的这种基于聊天软件的共享一个“信道”的约战方式效率低下，对于社恐的人也非常不友好。也许并不是所有人，但是社恐的人希望的是不聊天也能进行对战。

自动匹配和p2p似乎并不矛盾。服务端可以只进行匹配，不负责游戏同步。（也许只是存储、读取当前时间正在等待的主机信息就可以）

也许使用一部分活跃玩家的PC作为服务端？毕竟这游戏没什么负载量。玩家内部可以自行决定「哪些server负责哪个地区」，玩家可以只添加代表自己的地区的server，这样也可以分区匹配。

**Comment by RUEEE** [comment]
如果想进行p2p连接简单情况下需要至少一个人有公网ip,而如果利用服务端进行UDP打洞然后再p2p的话感觉有点复杂, 而且也是有一些问题的(<-反正我不会ﾐ(:３っ　)っ)
如果用一部分活跃玩家的pc做客户端的话首先你需要这些玩家一直在线,这几乎是不可能的
总之这个便宜补丁大概只是用来非随机的p2p连接的...
*如果是社恐的话为什么不能用匿名聊天程序发送ip进行约战呢(x

**Comment by karaika10** [comment]
匿名聊天程序实际上和我想要的东西非常接近。
但是聊天程序仍然是一个线性的信息流，一个想玩游戏的人需要
- 向上划并找到一个主机
- 如果找到了需要确认这个主机在尚未关闭
- 如果没找到合适的主机就自己建房

这显然不如一键匹配直观和高效。**更重要的是社恐的人是组织不起来这样的系统的**。让不社恐的人也加入这个系统更是难上加难，除非一个**领头者**牵头这件事，比如这个项目的作者。

---

我不知道我们之间有没有误解，“服务端”应该是一个**与游戏内容完全无关的 ip 分发器**，它不需要启动游戏，仅仅是保存和返回正在等待的 ip ，其他什么都不做。扮演“服务端”的玩家不需要一直开着游戏，他只需保持开机并且让“分发器”一直在后台运行即可，任意时刻该地区只要有一个“服务端”玩家处于开机状态就能进行联机。这好像并不难。

如果有现成的轮子欢迎指出，但是仍然需要有重要人物牵头。

**Comment by RUEEE** [comment]
那就与我无关了
反正我也没服务器.jpg
说到底你看这个项目本身现在才刚过10个star
就算我做出来了 能有几个人用呢(
其次 服务端的要求很高, 首先至少需要保证拥有公网ip, 而且为了保证每个人能连上, 还需要保证防火墙能透过去, 而且还要能在很长的时间(至少是大多数玩家有空的时间)不关闭电脑

再其次  假设服务端有了, 如何让打开游戏的人知道服务端的ip, 以及保证匹配到对的人, 如果认为可以手动配置ip, 那如何确保总是有服务端在线, 如果认为存在一个"服务端"ip分发网站, 那为什么不直接用那个网站作为服务端

再再其次 假设服务端有了, 也可以用比如配置文件配置, 如何确保不会有人对服务端攻击 (需要注意的是你所希望的服务端通常个人电脑与普通玩家, 无法防御这种攻击), 或者通过查ip之类的方式进行开盒(仍然要注意, 服务端必须拥有公网ip, 也因此可以被直接开盒)(尽管目前的p2p下只要放的是公网ip 也可以这样开盒, 但是由于被限定在了两个玩家, 而且两个玩家必然提前联系好了, 因此并不会产生过多的危险)

再再再其次 一旦假定你真的做出来了这一大坨玩意, 如何确保玩家之间的匹配是好的, 此处的好的不仅是指网络, 注意到你用词中出现了社恐人, 显然假设一个游戏高手和一个刚玩游戏的选手是不希望被匹配到的, 尤其对于社恐而言:  假设社恐是高手, 那么他不希望匹配到一个低手, 因为社恐高手不愿意薄纱别人从而破坏他人的游戏体验; 而如果社恐是个低手, 那么他如果匹配到了一堆高手, 显然他会更加自闭, 也不玩了; 由此可见, 你肯定需要一个段位系统或者之类的玩意, 但是显然这个系统并不好提供, 如果你认为可以自己手动设置匹配水平, 那么又如何防止炸鱼, 如果你认为这个同等水平匹配不是必要的, 那显然对社恐不友好, 甚至不如在群聊中寻找同道中人

再再再再其次 我也没那么闲去做这种东西

**Comment by karaika10** [comment]
@RUEEE 
从你的措辞中我能感觉到你是不会(won't)做了，我尊重这个选择。

但是也许其他代码贡献者会做呢？所以我仍然想罗列一些关于可行性的提议。

你更多的是只过滤并罗列了「不利的因素」，让这个提案显得非常糟糕。实际上项目的可行性应该是综合考虑「有利的因素」和「不利的因素」。
比如：
> 说到底你看这个项目本身现在才刚过10个star
> 就算我做出来了 能有几个人用呢(

那按这么说这个项目是不是从一开始就不应该存在？反正也没人用。
还有比如「炸鱼」的问题，我们当然不希望看到炸鱼，但这个问题重要程度显然不高。但是作为对反方有利还是被提出了。
这更像是「我不是既得利益者，所以我没有动力做，但是我不能直接说」，我很理解这种想法（如果这个猜测符合事实的话），我也是这样的人。

---

关于服务端PC的风险问题。试先郑重警告风险，并让玩家自己承担责任就好了。
（真的没有不公示公网 ip 的方法吗？也许只是我们还不知道？）（中间套一层壳怎么样、事先组网呢？（我完全不懂）（不限于这些方法））

不用确保「总是有服务端在线」。不在线就回到老方法。

「如何匹配到合适的对手」是个问题，但是这完全不是社恐人关心的，社恐人只是不想做没有营养的交谈和评论，其他的都可以忍受。

我们确实可以增加除了 ip 之外的信息（比如自己的水平和所在地区、对对手的要求）来确保匹配更精确。
炸鱼问题不是大问题，用聊天软件也可以建小号炸鱼不是。

服务端 ip 由每个用户手动配置，从「可用 ip 列表」中选择，填写适合自己地区的。「可用 ip 列表」可以放在封闭的社交圈的公共资源里（比如群文件）。

---

让我举个例子「群聊方式」和「自动方式」的效率的不同。（有利的因素）
``` text
有园吗
【中间穿插与此无关的对话】
有，你还在吗
【中间穿插与此无关的对话】
在
谁建房？
你建吧
114.51.41.91:9810
连上了
```
请注意这些对话会同时在一个聊天框里穿插进行。

自动方式：按一个键，显示正在创建的 ip 列表，选一个，自动开始游戏。只需两下点击，不需要打一个字。原本的群聊聊天框也会更清净。如果你就是想指定一个特定的对手，老方法也仍然可用。
