### ISSUE TITLE
thcrap support

### ISSUE THREAD

**Issue by williewillus** [RUEEE/th19p2vp#3]
It would be great if this patch was compatible with and could be installed via thcrap https://github.com/thpatch/thcrap/

**Comment by RUEEE** [comment]
i will try it but first i need to familiarize with thcrap...since i havn't modded on thcrap before(except some simple texture/code changes 
 (:з」∠)_

**Comment by williewillus** [comment]
If you're able to, you can try joining the thpatch discord https://discord.com/invite/XZygBsU
I'm sure they can help you out with getting it compatible

**Comment by RUEEE** [comment]
it should be compatiable with thcrap now...
though only a few test is done
