### ISSUE TITLE
Easy way to build / Building tutorial

### ISSUE THREAD

**Issue by rostuhan** [RUEEE/th19p2vp#7]
I think that there's no special file for building this patch from its source code right now, correct me if I'm wrong please. It would be really nice to have one, so if contributors want to test their contribution easily, they can use the building file. It would also be very nice to have a tutorial file for building.

**Comment by rostuhan** [comment]
Update: I've actually found some files that as I understand require Visual Studio to compile the project. It would still be nice to have a tutorial file, though.

**Comment by RUEEE** [comment]
what's your problem(or VS warning/errors) ?
the only extra needs for the project is windows SDK and Direct3D SDK...
the first one can be easily installed via VS and the second one needs to download
so the only thing is to download D3D SDK and add the corresponding path to include / library path...

**Comment by rostuhan** [comment]
Hello, I don't really have any problems, since I haven't even tried to compile it, but I'm just suggesting to create a tutorial file that tells about this and other compiling details.

**Comment by lilmayu** [comment]
From just my testing, as they said:
- DirectX SDK
- Windows SDK

**and compile only in x86.**

Maybe would be pretty cool to add the ability to compile THCRAP or not automatically (I think it's possible to set the THCRAP define from some settings in VisualStudio, so you don't have to comment / uncomment the `#define THCRAP`)

**Comment by RUEEE** [comment]
of course with/without thcrap can be a setting, but i'm too lazy to do this  _(:з」∠)_
anyway i added some compile tips in readme.
