### ISSUE TITLE
Gamepad not working with the game

### ISSUE THREAD

**Issue by Jonath** [RUEEE/th19p2vp#9]
Apparently this patch doesn't support gamepads? I had a friend connect to me and he was able to use his gamepad properly in story mode but once he connected to me, it defaulted him back to the keyboard (as P2).

I see it is mentioned in your README.md that you didn't test it because you only have keyboard.

If you want, since I have a gamepad myself too, I'd happily test a change for the way it is handled, if you could please direct me to the part of the code in charge of the inputs?

**Comment by Jonath** [comment]
More information on this: we tested with another controller that supports XInput. This one actually works to some extent but my friend could not charge / focus even if he hosts himself.

The first gamepad we used was a DirectInput pad (USB Super RetroPort SNES) with an adapter. With it, if my friend hosts, we desync when he select vs mode with his controller. I think this means in that case the gamepad inputs are not sent at all through the network.

An alternative we used to play in the meanwhile is JoyToKey (mapping the gamepad to a keyboard) but this isn't perfect as it adds input lag.

**Comment by RUEEE** [comment]
i tried to use vjoy to test this one
it might support gamepad, but might not(  (¦3____]
https://github.com/RUEEE/th19p2vp/releases/download/106/th19p2vp-1.06test.zip

**Comment by Jonath** [comment]
Thank you, this patch actually makes the DirectInput controller work perfectly well.

However we still face issues with the XInput controller (as I mentioned, my friend not being able to use focus and charge buttons, despite trying to map them beforehand).

Still a worthy improvement however, thanks for the update!

**Comment by RUEEE** [comment]
that's a bit weird since other keys are fine..
have your friennd tried to play the game without connecting? (like story mode)
or whether all buttons were pressed and no button could focus/charge?
also have you tried to remove the normal cfg(%appdata%/shanghaialice/th19/th19.cfg) then try all buttoms again?
these might be helpful for debug...

**Comment by Jonath** [comment]
It's actually pretty weird. If my friend starts hosting, it unlocks his controls (they are by default locked, I believe so that he doesn't move to keep synchronisation after connection). He can properly play story mode with all his controls that way (including charge / focus). However, after connecting with him right afterwards and trying to play a match, he loses these buttons once again. This may mean there is a bug in the code loading profiles during connection for XInput controllers?

I tried to use an XInput controller as well and found a similar issue on my end, although a bit different: I could use focus and charge properly but had no button dedicated to my base shot (it was mapped to the same button as one used to charge up). As a result, I ended up with 2 buttons to charge up, one of which was also related to base shot (but the base shot would get cut by the charge as it has more priority).

**Comment by RUEEE** [comment]
tried to fix it... the c++ auto might be the reason( should be int, but "auto" deduce a short)
https://github.com/RUEEE/th19p2vp/releases/download/106/th19p2vp-1.06test-b.zip

**Comment by Jonath** [comment]
This seems to do the trick, thank you very much!
I tested this fix with 2 players, using their XInput controllers:
- The first one using an actual XBox 360 controller, everything worked perfectly fine
- The second one (the previous player I mentioned) could also use their inputs properly (with a Nacon Gaming GC-100XF)

If you think this is good enough, I'll let you close out this issue and make a dedicated release for it?
